<#
Load CSV data files generated by `scripts/csv_seed.ts` using LOAD DATA LOCAL INFILE.

Usage:
  1) Generate CSVs: bun run scripts/csv_seed.ts
  2) Copy CSVs to DB server if necessary (or run locally if MySQL allows LOCAL INFILE)
  3) Run this script from repo root: .\scripts\load_data.ps1

Notes:
 - This script assumes you can use LOAD DATA LOCAL INFILE. If not, you must copy files to server and use LOAD DATA INFILE without LOCAL.
#>

Param()

Set-Location -Path (Resolve-Path "$PSScriptRoot\..")

$dbUser = 'root'
$dbName = 'auto24'

Write-Host "Loading CSV parts from ./data into database $dbName"

function runLoad([string]$file, [string]$table, [string]$columns) {
  Write-Host "Loading $file -> $table"
  $sql = "LOAD DATA LOCAL INFILE '$file' INTO TABLE $table FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES ($columns);"
  # Use mysql client to run
  & mysql -u $dbUser -p -D $dbName -e $sql
}

# Load makes and models (single files)
runLoad((Resolve-Path .\data\makes.csv), 'makes', 'name')
runLoad((Resolve-Path .\data\models.csv), 'models', 'make_id,name')

# Load users parts
Get-ChildItem -Path .\data -Filter 'users_part_*.csv' | Sort-Object Name | ForEach-Object {
  runLoad($_.FullName, 'users', 'id,username,email,password_hash,created_at,updated_at,is_active')
}

# Load vehicles parts
Get-ChildItem -Path .\data -Filter 'vehicles_part_*.csv' | Sort-Object Name | ForEach-Object {
  runLoad($_.FullName, 'vehicles', 'model_id,vin,year,price,description,engine,mileage,fuel_type,transmission,doors,seats,location,user_id,created_at')
}

# Load images parts
Get-ChildItem -Path .\data -Filter 'vehicle_images_part_*.csv' | Sort-Object Name | ForEach-Object {
  runLoad($_.FullName, 'vehicle_images', 'vehicle_id,image_url,is_cover')
}

Write-Host "Recreating indexes"
mysql -u $dbUser -p -D $dbName -e "CREATE INDEX idx_models_make_id ON models (make_id); CREATE INDEX idx_vehicles_model_id ON vehicles (model_id); CREATE INDEX idx_vehicles_user_id ON vehicles (user_id); CREATE INDEX idx_vehicle_images_vehicle_id ON vehicle_images (vehicle_id);"

Write-Host "Done. Verify counts with: mysql -u $dbUser -p -e \"SELECT COUNT(*) FROM users; SELECT COUNT(*) FROM vehicles; SELECT COUNT(*) FROM vehicle_images;\" $dbName"
